explanations/attribute-ordering.md
lib/derivation-attributes.nix
overlays/attribute-ordering.nix
overlays/missing-phase-hooks.nix
run-tests.py
tests/attribute-ordering/default.nix
tests/attribute-ordering/out-of-order.nix
tests/attribute-ordering/properly-ordered.nix
tests/default.nix

Based on https://discourse.nixos.org/t/document-attribute-ordering-in-package-expressions/4887.
cc @worldofpeace

attribute-ordering: Add attribute ordering check

---

README.md
lib/default.nix
tests/default.nix
tools/nixpkgs-hammer

Instead of printing the warnings in the `checkMkDerivationFor` function in Nix using `builtins.trace`, let’s pass the messages through an attribute and extract them as a JSON object during evaluation triggered by the tool.
This will rid us of the ugly “trace: ” prefix and also allow us to more easily control which overlays are used.
To make this easier, I also ported the tool to Python. Getting rid of bash is always nice.
cc @SuperSandro2000

Move printing of messages to the tool

---

lib/default.nix
overlays/attribute-ordering.nix
overlays/build-tools-in-build-inputs.nix
overlays/explicit-phases.nix
overlays/fixup-phase.nix
overlays/meson-cmake.nix
overlays/missing-phase-hooks.nix
overlays/patch-phase.nix
overlays/unclear-gpl.nix
overlays/unnecessary-parallel-building.nix

This will allow us to reuse it for other package sets like Python.
cc @rmcgibbo

lib: Split checkMkDerivationFor into multiple functions

---

lib/default.nix
lib/standalone.nix
tools/nixpkgs-hammer

It probably never worked. Instead of crashing, let’s return `null` so that this can be detected in assertions.
Also fix `--show-trace` so that developers can see debug issues more easily.
cc @rmcgibbo

Fix AttrPathNotFound detection

---

explanations/license-missing.md
explanations/maintainers-missing.md
overlays/license-missing.nix
overlays/maintainers-missing.nix
run-tests.py
tests/default.nix
tests/license-missing/default.nix
tests/license-missing/empty-license.nix
tests/license-missing/have-license.nix
tests/license-missing/no-license.nix
tests/license-missing/no-meta.nix
tests/maintainers-missing/default.nix
tests/maintainers-missing/empty-maintainers.nix
tests/maintainers-missing/have-maintainers.nix
tests/maintainers-missing/no-maintainers.nix
tests/maintainers-missing/no-meta.nix

n.b. I think we could probably improve the wording of the explanations and the warning message.

Add two simple checks from #1

---

explanations/attribute-typo.md
lib/levenshtein.nix
overlays/attribute-typo.nix
run-tests.py
tests/attribute-typo/casing.nix
tests/attribute-typo/default.nix
tests/attribute-typo/deletion.nix
tests/attribute-typo/insertion.nix
tests/attribute-typo/transposition.nix
tests/default.nix
tools/nixpkgs-hammer

This is somewhat common issue (e.g. https://discourse.nixos.org/t/create-development-environment-based-on-shell-nix/10035). Let's steal @infinisil's levenshtein functions.

Add 'attribute-typo' check

---

ast-checks/src/bin/missing-patch-comment.rs
ast-checks/src/bin/no-uri-literals.rs
ast-checks/src/bin/unused-argument.rs
ast-checks/src/common_structs.rs
run-tests.py
tests/default.nix
tests/unused-argument/default.nix
tests/unused-argument/unused-pattern-var-as-key.nix
tests/unused-argument/unused-pattern-var-in-let-binding.nix
tests/unused-argument/unused-pattern.nix
tests/unused-argument/unused-single.nix
tests/unused-argument/used-pattern.nix
tests/unused-argument/used-single.nix

Still some work to be done, but I wanted to file the WIP before signing off for the night.
1. ~Doesn't handle `func = a: 1;`-type functions yet, only handles functions where the formal parameters are in a pattern struct (obviously needs to be fixed).~
2.  Not every possible unused argument is actually caught -- a construct  `{foo}: {foo = 1;}` will not show as having an unused argument even though it does, because the keyvalue key foo in the function body will be incorrectly identified as a use of the formal parameter. This might not actually need to be fixed.
3. Other scoping like with and let blocks that introduce new variables and cause variables in the outer scope to be shadowed aren't taken into account, so that's another source of false negatives.
But re (2,3), I don't think false …

Add unused-argument check

---

tools/nixpkgs-hammer

Fixes: #35 
Perhaps we should show why the package does not evaluate but I do not see how to get the eval error with `tryEval`.

tool: Handle eval errors

---

explanations/missing-phase-hooks.md

Sandro explained this here: https://github.com/NixOS/nixpkgs/pull/112897#issuecomment-778199962, and I hadn't actually realized why this check was so important until he said it.

Add to missing-phase-hooks explanation

---

tools/nixpkgs-hammer

`EDITOR=echo nix edit` is rather ridiculous. It turns out it's implemented by calling `meta.position` (https://github.com/NixOS/nix/blob/master/src/nix/edit.cc#L34 and https://github.com/NixOS/nix/blob/master/src/libexpr/attr-path.cc#L108), so why not do that ourselves and avoid starting up an extra 2 processes.

tool: simplify extraction of filename associated with each attr

---

ast-checks/src/bin/missing-patch-comment.rs
ast-checks/src/tree_utils.rs
run-tests.py
tests/missing-patch-comment/complex-structure1.nix
tests/missing-patch-comment/default.nix
tests/missing-patch-comment/ignore-nested-lists1.nix
tests/missing-patch-comment/ignore-nested-lists2.nix

The change here is that within the value associated with the `patches` key, we branch on whether the value is a List. If it is, we look for a comment above every entry. If it's not, we look for any lists contained within it, and look for a comment above every entry in each of these sub-lists.
As far as I can tell, the vast majority of 'patches' entries in nixpkgs are, at an AST level, either:
- a list (handled well)
- some function applied to a list (like lib.optional)
- a binary operator  (like `++`)  acting on nodes that are lists or functions applied to lists
Unlike the code before, I can't think of any false positives that this version will emit. It will, however, fail to emit a warning (false negatives) if the AST doesn't actually use a list node in the file we're linting, like:
``` …
```

Fix issue #23

---

run-tests.py
tests/EvalError/default.nix
tests/EvalError/exception.nix
tests/EvalError/no-exception.nix
tests/default.nix
tools/nixpkgs-hammer

Before:
```
nix run -f . -c nixpkgs-hammer -f ~/projects/nixpkgs python39Packages.pylint --json
error: --- ThrownError ----------------------------------------------------------------------------------------------------------- nix-instantiate
astroid-2.4.2 not supported for interpreter python3.9
(use '--show-trace' to show detailed location information)
Traceback (most recent call last):
File "/nix/store/188vld53372z94cgva6bbpgd4hgjl41r-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 294, in <module>
main(args)
File "/nix/store/188vld53372z94cgva6bbpgd4hgjl41r-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 222, in main
overlay_data = nix_eval_json(all_messages_nix, args.show_trace)
File "/nix/store/188vld53372z94cgva6bbpgd4hgjl41r-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 65, …
```

Fix evaluation of attrs that dependent on disabled packages

---

lib/derivation-attributes-unordered.nix

Fixes
```
citrix_workspace:
A likely typo in dontAutoPatchelf argument was found, did you mean dontPatchELF?
Near pkgs/applications/networking/remote/citrix-workspace/generic.nix:195:3:
────────────────────
|
195 |   dontAutoPatchelf = true;
|   ^
────────────────────
See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/attribute-typo.md                                                                                                                                                                                            ```

attribute-typo: whitelist dontAutoPatchelf

---

overlays/no-flags-spaces.nix
run-tests.py
tests/no-flags-spaces/default.nix
tests/no-flags-spaces/nonstring.nix

Fixes #68.
I considered making a bigger modification where I throw a different error message if the types are not as expected, but I think it might be better to do that feature for a wider set of attributes using a dedicated approach.

checks: prevent 'no-flags-spaces' from throwing a type error

---

tools/nixpkgs-hammer

Prevents something like `nixpkgs-hammer -f . --json  haskellPackages.if` from crashing.

tool: escape attr names when passing to nix

---

overlays/missing-phase-hooks.nix

There's an obvious type error in this file... https://github.com/NixOS/nixpkgs/blob/20.09/pkgs/development/compilers/dasm/default.nix#L14
```
$ nixpkgs-hammer -f . --json dasm
error: --- TypeError ------------------------------------------------------------------------------------------------------------- nix-instantiate
at: (22:24) in file: /nix/store/a4kmahx6mq7sb5x4hxvwn4wlkad5ybzc-nixpkgs-hammer/overlays/missing-phase-hooks.nix
21|         let
22|           preMissing = builtins.match ".*runHook pre${capitalize phase}.*"  drvArgs."${phase}Phase" == null;
|                        ^
23|           postMissing = builtins.match ".*runHook post${capitalize phase}.*" drvArgs."${phase}Phase" == null;
value is a Boolean while a string was expected
(use '--show-trace' to show detailed location …
```

missing-phase-hooks: be more tolerant of type errors in nixpkgs

---

overlays/python-include-tests.nix

Fixes
```
nixpkgs-hammer -f . --json  python39Packages.alot
error: --- TypeError ------------------------------------------------------------------------------------------------------------- nix-instantiate
at: (18:69) in file: /nix/store/mn57a9kgk0yc7y0a4rd8xvfaqj3rfbii-nixpkgs-hammer/overlays/python-include-tests.nix
17|           hasDoCheckFalse = (drvArgs ? doCheck) && (drvArgs.doCheck == false);
18|           hasPytestCheckHook = drvArgs ? checkInputs && lib.any (n: n.name == "pytest-check-hook") drvArgs.checkInputs;
|                                                                     ^
19|           hasPythonImportsCheck = drvArgs ? pythonImportsCheck;
value is null while a set was expected
(use '--show-trace' to show detailed location information)
Traceback (most recent call …
```

python-include-tests: fix possible type error

---

overlays/attribute-ordering.nix

Fixes the following crash, against nixpkgs edb5000ea3e02c8fe1caba17c6c329066d6d8ae9
```
$ nixpkgs-hammer -f . warsow-engine
[1 built, 0.0 MiB DL]
error: --- TypeError ------------------------------------------------------------------------------------------------------------- nix-instantiate
at: (33:27) in file: /nix/store/0gsly7wzm6pkq7x8q8fzs24npsxmzjd5-nixpkgs-hammer/overlays/attribute-ordering.nix
32|       getAttrPos = attr: (builtins.unsafeGetAttrPos attr drvArgs);
33|       getAttrLine = attr: (getAttrPos attr).line; #or 0;
|                           ^
34| 
value is null while a set was expected
(use '--show-trace' to show detailed location information)
Traceback (most recent call last):
File "/nix/store/0gsly7wzm6pkq7x8q8fzs24npsxmzjd5-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", …
```

attribute-ordering: fix possible crash

---

lib/derivation-attributes.nix

```
joplin:                                                                                                                                                                                     <details>                                                                                                                                                                                                                                                                                                                                                                               warning: attribute-typo                                                                                                                                                                     A likely typo in dontNpmInstall argument …
```

attribute-typo: allow dontNpmInstall

---

lib/derivation-attributes.nix

```
nixpkgs-hammer python37 --exclude attribute-ordering
When evaluating attribute ‘python37’:
warning: attribute-typo
A likely typo in `CPPFLAGS` argument was found, did you mean `CFLAGS` or `CXXFLAGS`?
Near /home/hotpi/.cache/nixpkgs-review/pr-114530-3/nixpkgs/pkgs/development/interpreters/python/cpython/default.nix:242:3:
|
242 |   CPPFLAGS = concatStringsSep " " (map (p: "-I${getDev p}/include") buildInputs);
|   ^
See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/attribute-typo.md
```

attribute-typo: whitelist CPPFLAGS

---

overlays/build-tools-in-build-inputs.nix

build tools: remove yacc

---

overlays/python-include-tests.nix
tests/python-include-tests/no-tests-no-import-checks.nix

no-python-tests also fired when a package uses `setuptools-check-hook`,
which is the default for `format = "setuptools"`.
This change also makes the test more robust. Checks in Python packages
are actuall install checks, however `buildPythonPackage` also accepts
`doCheck`/`checkInputs`, which are then used to set
`doInstallCheck`/`installCheckInputs`. Consequently, it is also valid for
a derivation to use `doInstallCheck`/`installCheckInputs` instead.
To complicate matters, we cannot just check derivation arguments,
since `buildPythonPackage` also sets `doInstallCheck/installCheckInputs`
when the project format is `setuptools`.
This change updates the test to look for check hooks in the
`nativeBuildInputs` of the final derivation. As well as checking
whether install checks are enabled.

python-include-tests: fix errors when setuptools-check-hook is used

---

rust-checks/src/bin/missing-patch-comment.rs

I messed up #114 by accidentally deleting the branch rather than force-pushing when trying to respond to the review.

missing-patch-comment: tweak language of message

---

tools/nixpkgs-hammer

We use `builtins.tryEval` to reduce the chance a check crashes but that comes at a cost of harder debugging, since the function does not tell us anything about the error.
Let’s add a CLI flag that removes this check, to allow observing evaluation errors in their full glory (especially with --show-trace).

tool: Add flag to avoid catching eval errors

---

flake.lock
flake.nix

`buildRustPackage` now supports vendoring from `Cargo.lock` without a hash

flake: remove dependency on naersk

---

overlays/build-tools-in-build-inputs.nix

This results in identical symptoms to #127, and applying `--do-not-catch-errors` discovered that qmake4Hook removal was the culprit.

fix: qmake4Hook was removed from nixpkgs

---

flake.lock
overlays/build-tools-in-build-inputs.nix
run-tests.py

Fixes: https://github.com/jtojnar/nixpkgs-hammering/issues/150

build-tools-in-build-inputs: Do not crash when package is removed from Nixpkgs

---

.github/workflows/main.yaml
flake.lock

For some reason, the CI eventually started to fail on `flake-compat` not being able to import the `flake.nix` from the repo.
error:
… while evaluating attribute '"attribute-ordering.out-of-order"'
at «stdin»:31:5:
30| in {
31|     "attribute-ordering.out-of-order" =
|     ^
32|       let
… while evaluating a branch condition
at «stdin»:36:9:
35|       in
36|         if !(result.success && maybeReport.success) then
|         ^
37|           {
… in the argument of the not operator
at «stdin»:36:29:
35|       in
36|         if !(result.success && maybeReport.success) then
|                             ^
37|           {
… in the left operand of the AND (&&) operator
at «stdin»:36:29:
35|       in
36|         if !(result.success && maybeReport.success) then
|                             ^
37| …

ci: Fix tests
